### PR TITLE
Added NullTime, NullBytes & Null* helpers

### PR DESCRIPTION
**Pull request by derkan**
Null helpers&types 
- Types: ` NullTime, NullBytes`
- Helpers for initializing `Null*` values:  `NullBoolFrom, NullStringFrom, NullFloat64From, NullInt64From, NullTimeFrom, NullBytesFrom`

### CODE REVIEW

**Comment by derkan** [comment]
Hi Samuel,
Could you please review this pull request?
Thanks

**Comment by samonzeweb** [comment]
Hi Derkan,

I'm sorry, but I'm really busy at the moment.

Just an advice : you should use separate branches per features (not master one).

The NullXXXX helpers are useful. But I don't understand why using new types, as their carry no information (except sql.NullXXX), and they're not used as method receivers.

Why not simply create helpers like this one ?


```
func NullStringFrom(v string) sql.NullString  {
	return sql.NullString{String: v, Valid: true}
}
```

Another big problem is the change in dbreflect : https://github.com/derkan/godb/blob/master/dbreflect/scannable.go#L17

You didn't add new types, you changed existing code removing the use of sql.NullXXXX ones. Users should use sql.NullXXXX if it's their choice.

But if types.NullXXXX types are removed to just have helpers, the problems will be solved. 

Adding new Null types wrapping standard types like time.Time or []byte could be useful.

What I thing is :
* NullXXX helpers are useful, but no the associated type.
* Wrapping **standard** types (simple or from stdlib) in nullable new types is useful.
* keeping them together in a `types` sub package is ok.

In any case, thank you for your contribution.
Sam.

**Comment by derkan** [comment]
Thanks for review, it was useful. From your suggestions I'll make these changes:
- Remove, `Null*` type wrappers for `sql.*` types, but leave  `NullFrom*` helpers. ( I put sql.* wrappers for convenience, import single package and look types in a single place for IDE autocomplete. But it is not a must)
- Revert changes for `sql.*` types in `dbreflect`.
Erkan.

**Comment by derkan** [comment]
Hi Sam,
Please review changes when you have a time. 
I found this [document](https://gist.github.com/Chaser324/ce0505fbed06b947d962) very useful, and will try to use branch'es for my next pull request as you suggested. :-)
Erkan.

**Comment by samonzeweb** [comment]
I've merged the PR. I just made some correction in comments and doc, I think you made a *generous* replace of `nullable`with `types` ;)

Thanks for the contribution.

**Pull request closed without merging**
