### PR TITLE
added Wrap(sql.DB) for preconfigured sql.DB instance

### PR DESCRIPTION
**Pull request by derkan**
- Added Wrap function to use pre-configured sql.DB.
- Added  Null* helpers
- Some spelling corrections.

### CODE REVIEW

**Comment by samonzeweb** [comment]
Thanks Erkan for your contribution.

I appreciate the Wrap(), and the type corrections. I think some code could be shared with Open(), but I can do it myself later.

I've a problem with the helpers, because it's not really related to godb itself. These helpers could be in another package IMHO, either in your own project using godb, or something reusable. 

Could you change your pull request to have only the Wrap & corrections parts ? Then I'll merge it.

Sam.

**Comment by derkan** [comment]
Hi Sam,

Thanks for reviewing PR. `Null*` code is added as helpers and IMHO it will be helpful for users use `NULL` columns in structs. For example adding `PageCount  sql.NullInt64` to `Book` structure in your example in README and using it in an update will be: 
```go
var bookTheReturnOfTheKing = Book{
    Title:     "The Return of the King",
    Author:    authorTolkien,
   PageCount:sql.NullInt64{Int64:1, Valid:true}},
    Published: time.Date(1955, 10, 20, 0, 0, 0, 0, time.UTC),
}
``` 
which is open to user errors for defining `Valid` and `Int64` values consistently. Instead `NullInt64From` helper will be much easier and safer. It may be better to borrow this [file](https://github.com/gocraft/dbr/blob/master/types.go) project for JSON marshaling from dbr project.

At your README there isn't an example for mapping or setting this type of columns. I'll remove helper file if you are not comfortable about it and modify your example with adding a `sql.NullString` type to show how to use with types in `sql` package.

derkan

**Comment by derkan** [comment]
removed Null* helpers.

**Comment by samonzeweb** [comment]
I'll see the "Null" problem later. It's interesting, I just want to have time to thing about it. I've also noticed the lack of "Null" example.

Please, just keep the "Wrap" feature without adding other in the same pull request. I'll check it and merge it later (I'm not available for that now). One feature / PR please ;)

**Comment by derkan** [comment]
OK

**Comment by samonzeweb** [comment]
I've merged to MR. Thanks.

**Pull request merged**
