### PR TITLE
Wrapped `sql.Null*` for JSON marshall/unmarshall compability, added `types.NullTime` JSON

### PR DESCRIPTION
**Pull request by derkan**
Wrapped `sql.Null*` for JSON marshall/unmarshall compability and  also added JSON marshall/unmarshall compability to `types.NullTime`

### CODE REVIEW

**Comment by samonzeweb** [comment]
Hi Derkan,

All added code seems ok at first glance, but you broke the public API : NullStringFrom, NullFloat64From, ... have to returns the same types as before. If somebody else use your `types` sub-package it will have some troubles... 

New types need new helpers methods.

Sam.

**Comment by derkan** [comment]
Hi,
It will be breaking change, agree with that. But, consolidation of all `Null...` in types package will be better in developer's perspective. Otherwise some null types from sql package some from our package will be hard to remember.
E.D.

**Comment by samonzeweb** [comment]
Hi,

`godb` use [semantic versioning](https://blog.golang.org/versioning-proposal), and it's an important thing in the Go ecosystem, especially [since Go 1.11](https://blog.golang.org/go1.11) introduced **modules** : a breaking change would implies a new major version. A new major version implies new repository or sub-package prefixes with version.

Generally a new major version is planed with new features and/or major refactoring and/or some deprecations, ... , we could not create a new major version each time something is wrong. We could do that in the *preview* versions, when version numbers are 0.x.x and warning about changes is mentioned in the README. Of course there could be exception when a major security flaw has to be corrected... but it's not the case here.

If it was an internal, or only personnal projet, I would be more permissive. But other users could use `godb` and could be concerned by our breaking changes.

I think new types with new helpers methods is the only viable solution. And we could also add [deprecations notices ](https://rakyll.org/deprecated/) on *old* methods to prepare a later refactoring. Of course other suggestions are welcome, but we can't break the API.

Sam.

**Comment by samonzeweb** [comment]
Hi Derkan,

That seems ok :)

**Pull request merged**
